### ISSUE TITLE
what's meaning about `Cosine_Hash_from_file(0, L, k);` ?

### ISSUE THREAD

**Issue by muyuuuu** [CChatzis/Nearest-Neighbour-LSH#1]
In [here](https://github.com/cchatzis/Nearest-Neighbour-LSH/blob/master/modules/CosineHashing.cpp#L149-L158) erase the zero from `Hash_Tables`, but why run `Cosine_Hash_from_file(0, L, k);` ? Could you explain it? please.

**Comment by cchatzis** [comment]
Hello and thank you very much for your input. 

Vector `Hash_Tables` is initialized (resized actually) inside `void HashTable_Cosine_Initialization(int L,int k)`. During the resize procedure, the vector is filled with zeros of the given size. My goal at `void Hash_Tables_Finalization(int L, int k)` is to remove the zeros added by it. However, one of those zeros refers to the first line, which of course we have to keep. Thus, after removing all of the zeros, we need to run `Cosine_Hash_from_file(0, L, k)` to re-hash it and store it.

If anything is not clear, feel free to write back.

EDIT1: Removed suggested fix.
