### ISSUE TITLE
Some bugs in the consine program need to be noted

### ISSUE THREAD

**Issue by muyuuuu** [CChatzis/Nearest-Neighbour-LSH#2]
1. Similarity calculation error in cosine, arrording to [Cosine similarity Wiki](https://en.wikipedia.org/wiki/Cosine_similarity) `1-cos` is not required.
2. In [here](https://github.com/cchatzis/Nearest-Neighbour-LSH/blob/master/modules/CosineHashing.cpp#L25-L37), dimensional mismatch of hash functions clearly.
```cpp
Hash_Function.resize(dimension ,vector<double>(k));
for(int i=0;i<k;i++){
  Hash_Function[i].clear();
  for(int j=0;j < dimension;j++){
      Hash_Function[i].push_back(normal_distribution_generator() );
  }
}
```
Some cumbersome code can be avoided as describion in #1  if the above bug is fixed.
3. [Here](https://github.com/muyuuuu/SeetaFace-Retri/tree/main/CosineLSH/modules) is my reimplement if you are insterested in it.

**Comment by cchatzis** [comment]
Again, thank you for your time and for pointing out those errors. (1) and (2) were addressed in 456758fc3d00327ab3e9e080debae444beb9598e.

I will definitely have a look at your implementation, even though I don't know Chinese :)
